Hippo.Web/Views/Shared/Components/DynamicScripts/Default.cshtml, Hippo.Web/Views/Shared/Components/DynamicScripts/DynamicScripts.cs, Hippo.Web/Views/Shared/Components/DynamicStyles/DynamicStyles.cs
=> fix namespace

Hippo.Core/Domain/Account.cs, Hippo.Core/Migrations/SqlServer/20220203221517_AccountName.Designer.cs, Hippo.Core/Migrations/SqlServer/20220203221517_AccountName.cs, Hippo.Core/Migrations/SqlServer/AppDbContextSqlServerModelSnapshot.cs, Hippo.Core/Migrations/Sqlite/20220203221508_AccountName.Designer.cs, Hippo.Core/Migrations/Sqlite/20220203221508_AccountName.cs
=> Sponsor name

Hippo.Core/Services/SshService.cs, Hippo.Web/Controllers/TestController.cs
also updated service code to clean up usings
=> example of uploading file to hpc

Hippo.Web/ClientApp/src/AppNav.tsx, Hippo.Web/Controllers/AccountController.cs
=> Logout... but needs style

Hippo.Core/Services/EmailService.cs, Hippo.Email/Models/DecisionModel.cs, Hippo.Email/Views/Emails/AccountDecission.cshtml, Hippo.Email/Views/Emails/AccountDecission_mjml.cshtml, Hippo.Email/Views/Emails/AccountRequest.cshtml, Hippo.Email/Views/Emails/AccountRequest_mjml.cshtml, Hippo.Web/Controllers/TestController.cs
=> Decision email

Hippo.Email/Models/DecisionModel.cs, Hippo.Email/Models/NewRequestModel.cs, Hippo.Email/Views/Emails/AccountDecission.cshtml, Hippo.Email/Views/Emails/AccountRequest.cshtml, Hippo.Email/Views/Shared/_EmailLayout_mjml.cshtml
So when it changes to hippo we don't have to regenerate emails
=> Use model for logo url

Hippo.Core/Data/AppDbContext.cs, Hippo.Core/Data/DbInitializer.cs, Hippo.Core/Domain/Account.cs, Hippo.Core/Hippo.Core.csproj, Hippo.Web/ClientApp/src/App.test.tsx, Hippo.Web/ClientApp/src/components/Home.tsx, Hippo.Web/ClientApp/src/components/RequstForm.tsx, Hippo.Web/ClientApp/src/test/mockData.ts, Hippo.Web/ClientApp/src/test/testHelpers.ts, Hippo.Web/ClientApp/src/types.ts, Hippo.Web/ClientApp/src/util/api.ts, Hippo.Web/Controllers/AccountController.cs, Hippo.Web/Controllers/SuperController.cs, Hippo.Web/Hippo.Web.csproj, Hippo.Web/Startup.cs
Added dynamic pulling of user account state, ability to create new accounts if you don't already have one.  Form fields not hooked up, account creation doesn't show status or go back to home.  Still need to determine routing methods and strategy.  But, first API controller interaction, gotta start somewhere.
=> some basic interactions

Hippo.Core/Data/DbInitializer.cs, Hippo.Web/Controllers/AccountController.cs
test of sending the ssh key to farm on approval.  it does work.  still needs emailing and history
=> save actual ssh file to remote location

Hippo.Core/Services/SshService.cs, Hippo.Web/Controllers/AccountController.cs, Hippo.Web/Controllers/TestController.cs
=> Upload and rename

Hippo.Web/ClientApp/src/components/AccountInfo.tsx, Hippo.Web/ClientApp/src/components/PendingApproval.tsx
=> Show the use name

Hippo.Web/ClientApp/src/components/AccountInfo.tsx, Hippo.Web/ClientApp/src/components/ApproveAccounts.tsx, Hippo.Web/ClientApp/src/components/PendingApproval.tsx, Hippo.Web/Controllers/AccountController.cs
=> Reject button

Hippo.Web/ClientApp/src/components/AccountInfo.tsx, Hippo.Web/ClientApp/src/components/AdminUsers.tsx, Hippo.Web/ClientApp/src/components/ApproveAccounts.tsx, Hippo.Web/ClientApp/src/components/PendingApproval.tsx, Hippo.Web/Controllers/AccountController.cs, Hippo.Web/Controllers/AdminController.cs
=> Add admin user

Hippo.Web/Startup.cs
=> When CAS doesn't return claims

Hippo.Web/ClientApp/src/AppNav.tsx, Hippo.Web/ClientApp/src/Shared/ShowFor.tsx
=> Use the router NavLink

Hippo.Email/Views/Emails/AccountDecission.cshtml, Hippo.Email/Views/Emails/AccountDecission_mjml.cshtml, Hippo.Email/Views/Emails/AccountRequest.cshtml, Hippo.Email/Views/Emails/AccountRequest_mjml.cshtml
Still need to generate the email
=> fix email button link

Hippo.Core/Services/UserService.cs, Hippo.Web/Controllers/SystemController.cs, Hippo.Web/Extensions/ClaimsExtensions.cs, Hippo.Web/Startup.cs, Hippo.Web/Views/Shared/_Layout.cshtml
closes #90 
Feel free to suggest better names.
=> Get from the DB

Hippo.Web/ClientApp/src/components/Admin/Sponsors.tsx, Hippo.Web/Controllers/AdminController.cs
=> Update if exists or add and then sort

Hippo.Core/Services/NotificationService.cs, Hippo.Email/Models/DecisionModel.cs, Hippo.Email/Views/Emails/AdminOverrideDecission.cshtml, Hippo.Email/Views/Emails/AdminOverrideDecission_mjml.cshtml, Hippo.Web/Controllers/AdminController.cs, Hippo.Web/Controllers/TestController.cs
closes #111 
Admin is CC'd on the email. Can remove that if desired.
=> Notify sponsor of an admin override of account request

Hippo.Web/ClientApp/src/components/Account/RequestForm.tsx
=> mailto to add sponsor

Hippo.Web/ClientApp/src/components/Account/PendingApproval.tsx, Hippo.Web/ClientApp/src/components/Account/RequestForm.tsx, Hippo.Web/Controllers/AccountController.cs
=> rsa public key and pending page text

Hippo.Core/Data/AppDbContext.cs, Hippo.Core/Data/DbInitializer.cs, Hippo.Core/Domain/Account.cs, Hippo.Core/Domain/Cluster.cs, Hippo.Core/Domain/User.cs, Hippo.Core/Migrations/SqlServer/20220321212517_cluster.Designer.cs, Hippo.Core/Migrations/SqlServer/20220321212517_cluster.cs, Hippo.Core/Migrations/SqlServer/20220321220631_cluster2.Designer.cs, Hippo.Core/Migrations/SqlServer/20220321220631_cluster2.cs, Hippo.Core/Migrations/SqlServer/AppDbContextSqlServerModelSnapshot.cs, Hippo.Core/Migrations/Sqlite/20220321212509_cluster.Designer.cs, Hippo.Core/Migrations/Sqlite/20220321212509_cluster.cs, Hippo.Core/Migrations/Sqlite/20220321220623_cluster2.Designer.cs, Hippo.Core/Migrations/Sqlite/20220321220623_cluster2.cs
=> Db structure for Cluster

Hippo.Core/Services/NotificationService.cs
=> email button url

Hippo.Web/Controllers/AdminController.cs
=> Change account owner.

Hippo.Web/ClientApp/src/AppNav.tsx
=> If there is a cluster selected, redirect to the root of that, 

Hippo.Web/ClientApp/src/components/Admin/AdminUsers.tsx, Hippo.Web/ClientApp/src/components/Admin/Sponsors.tsx
=> confirm admin and sponsor removal

Hippo.Core/Services/HistoryService.cs, Hippo.Web/ClientApp/src/components/Account/ApproveAccounts.tsx, Hippo.Web/ClientApp/src/components/Admin/AdminApproveAccounts.tsx, Hippo.Web/ClientApp/src/components/Admin/AdminUsers.tsx, Hippo.Web/ClientApp/src/components/Admin/Sponsors.tsx, Hippo.Web/ClientApp/src/components/Admin/TransferSponsor.tsx, Hippo.Web/Controllers/AdminController.cs
transfer all people sponsored by one acct to another acct, creating if necessary.  
closes #113
=> transfer sponsorship 

Hippo.Core/Hippo.Core.csproj, Hippo.Core/Models/Settings/AuthSettings.cs, Hippo.Core/Services/IdentityService.cs, Hippo.Core/Services/UserService.cs, Hippo.Web/Hippo.Web.csproj, Hippo.Web/Startup.cs
Move identity service to core, update Ietws
=> Fix missing mothra

Hippo.Web/ClientApp/src/components/Account/RequestForm.tsx
Updated the contact info in RequestForm component for incumbents who's sponsor is not listed.
=> changed contact info for incumbents who's sponsor is not listed.

Hippo.Web/Controllers/AccountController.cs, Hippo.Web/Services/YamlService.cs
=> Added cluster param to YamlService to pass cluster info to YamlService.

Hippo.Web/Controllers/AccountController.cs
fix for duplicate accounts issue #208
=> added condition to ensure account status != Rejected

Hippo.Core/Domain/Group.cs, Hippo.Core/Services/AccountSyncService.cs, Hippo.Web/ClientApp/src/components/Account/ActiveAccounts.tsx, Hippo.Web/ClientApp/src/components/Admin/Groups.tsx, Hippo.Web/Controllers/GroupController.cs
And remove group delete button, since that is now done by `AccountSyncService`.
=> Sync all groups and simplify account sync queries

Hippo.Web/ClientApp/src/components/Admin/Groups.tsx
It's no longer necessary, since all groups are now being synced by the `AccountSyncService`
=> Remove group create form

Hippo.Web/Controllers/AccountController.cs
Closes #225 
There are also some problems with the information being logged in `AccountController.Create()`, but that's not as urgent, requires more extensive changes, and is already being addressed in the `dev` branch.
=> Only allow updates of active accounts

Hippo.Core/Extensions/StringExtensions.cs, Hippo.Web/ClientApp/src/components/Account/AccountInfo.tsx, Hippo.Web/ClientApp/src/components/Account/RequestForm.tsx, Hippo.Web/ClientApp/src/components/ClusterAdmin/Clusters.tsx, Hippo.Web/Controllers/AccountController.cs, Hippo.Web/Controllers/ClusterAdminController.cs, Test/StringExtensionsTests.cs
Not going as far as loading any encryption libraries to parse the ssh key. I think it's good enough just to ensure the base-64 encoded header matches the declared key type.
Closes #183
Closes #203
=> Improve ssh key handling and validation

Hippo.Web/ClientApp/src/components/Account/AccountInfo.tsx, Hippo.Web/ClientApp/src/components/Account/RequestForm.tsx, Hippo.Web/ClientApp/src/components/Admin/Groups.tsx, Hippo.Web/ClientApp/src/components/Home.test.tsx, Hippo.Web/Controllers/GroupController.cs
And get rid of unnecessary GroupNames action.
=> Ensure fetched groups include admin info

Hippo.Core/Migrations/SqlServer/20231103175231_HippoV2.cs, Hippo.Core/Services/AccountSyncService.cs
=> Fix a HippoV2 migration bug and account sync bug

Hippo.Core/Domain/Account.cs, Hippo.Core/Domain/Group.cs, Hippo.Core/Migrations/SqlServer/20231103175231_HippoV2.cs, Hippo.Core/Migrations/Sqlite/20231103175224_HippoV2.cs, Hippo.Core/Services/AccountSyncService.cs, Hippo.Web/ClientApp/src/components/Account/ActiveAccounts.tsx, Hippo.Web/ClientApp/src/components/Account/Requests.tsx, Hippo.Web/ClientApp/src/components/Admin/ClusterAdmins.tsx, Hippo.Web/ClientApp/src/components/Admin/Groups.tsx, Hippo.Web/ClientApp/src/components/ClusterAdmin/Clusters.tsx
=> A few more fixes for HippoV2

Hippo.Web/ClientApp/src/components/Account/Clusters.tsx, Hippo.Web/ClientApp/src/sass/_layout.scss, Hippo.Web/ClientApp/src/sass/_regions.scss
=> simple clean up

Hippo.Web/ClientApp/src/components/Account/RequestForm.tsx
=> Indicate how sponsors can initiate their own onboarding

Hippo.Core/Data/AppDbContext.cs, Hippo.Core/Domain/Account.cs, Hippo.Core/Domain/Group.cs, Hippo.Core/Domain/GroupAdminAccount.cs, Hippo.Core/Domain/GroupMemberAccount.cs, Hippo.Core/Domain/History.cs, Hippo.Core/Domain/Request.cs
=> Fix EF Core warnings about global query filters

Hippo.Web/ClientApp/src/components/Account/AccountInfo.tsx
=> Filter PendingRequests by cluster

Hippo.Core/Services/AccountUpdateYamlService.cs
=> Yaml should be renamed to remove prepended dot

Hippo.Core/Models/AccountDetail.cs, Hippo.Core/Services/UserService.cs, Hippo.Web/ClientApp/src/Shared/ObjectTree.tsx, Hippo.Web/ClientApp/src/Shared/ShowFor.tsx, Hippo.Web/ClientApp/src/Shared/UsePermissions.ts, Hippo.Web/ClientApp/src/components/Account/AccountInfo.tsx, Hippo.Web/ClientApp/src/components/Account/RequestForm.tsx, Hippo.Web/ClientApp/src/components/Admin/Groups.tsx, Hippo.Web/ClientApp/src/components/Group/GroupDetails.tsx, Hippo.Web/ClientApp/src/components/Group/GroupInfo.tsx, Hippo.Web/ClientApp/src/components/Group/GroupLookup.tsx, Hippo.Web/ClientApp/src/components/Group/GroupNameWithTooltip.tsx, Hippo.Web/ClientApp/src/components/Home.test.tsx, Hippo.Web/ClientApp/src/sass/_components.scss, Hippo.Web/ClientApp/src/util/ObjectHelpers.ts, Hippo.Web/ClientApp/src/util/TypeChecks.ts, Hippo.Web/ClientApp/src/util/api.ts, Hippo.Web/Views/Shared/_Layout.cshtml
=> Add display of group and account details/resources

Hippo.Web/ClientApp/src/components/Account/RequestForm.tsx
=> Redirect RequestForm to AccountInfo when account exists

Hippo.Core/Services/EmailService.cs, Hippo.Core/Services/NotificationService.cs, Hippo.Email/Models/DecisionModel.cs, Hippo.Email/Views/Emails/AccountDecision_mjml.cshtml, Hippo.Email/Views/Emails/AccountRequest_mjml.cshtml, Hippo.Email/Views/Emails/AdminOverrideDecision_mjml.cshtml, Hippo.Web/Controllers/RequestController.cs
Subjects are more specific. Additional details section moved up. Tweaked message in Approved decision details.
Subject: Hippo Request (Create Account) Submitted
Subject: Hippo Request (Create Account) Rejected
Subject: Hippo Request (Create Account) Approved 
closes #332
=> Notification Tweaks

Hippo.Core/Domain/History.cs, Hippo.Core/Models/SoftwareRequestModel.cs, Hippo.Core/Services/EmailService.cs, Hippo.Core/Services/HistoryService.cs, Hippo.Core/Services/NotificationService.cs, Hippo.Email/Models/DecisionModel.cs, Hippo.Email/Models/NewRequestModel.cs, Hippo.Email/Models/SampleModel.cs, Hippo.Email/Models/SimpleNotificationModel.cs, Hippo.Email/Views/Emails/SimpleNotification_mjml.cshtml, Hippo.Web/ClientApp/src/App.tsx, Hippo.Web/ClientApp/src/Shared/SearchPerson.tsx, Hippo.Web/ClientApp/src/components/ClusterAdmin/SoftwareRequestForm.tsx, Hippo.Web/ClientApp/src/constants.ts, Hippo.Web/ClientApp/src/types.ts, Hippo.Web/Controllers/PeopleController.cs, Hippo.Web/Controllers/SoftwareController.cs, Hippo.Web/Controllers/TestController.cs, Hippo.Web/Startup.cs
Currently there are no navigation links to the form, but it is accessible to authenticated users at `/softwarerequest`
Email to hpc-help@ucdavis.edu
Email to requester
Closes #341
=> Add form for custom software install requests

Hippo.Core/Domain/History.cs
History records with null clusterId were being filtered.
=> Quick fix for regression in "Last Synced..." message

Hippo.Core/Services/AccountSyncService.cs, Hippo.Core/Services/PuppetService.cs, Hippo.Core/Utilities/JsonHelper.cs, Hippo.Web/ClientApp/src/NotFound.tsx
=> Expand qos references during account sync

Hippo.Core/Services/PuppetService.cs, Hippo.Web/ClientApp/src/Shared/ObjectTree.tsx
And fix a transient auth error when debugging account sync job.
Closes #379
=> Add [Expand All] toggle to ObjectTree component

Hippo.Web/ClientApp/src/Shared/Form/FormSubmitButton.tsx
=> RH/reorganizing <- fix annoying submit button error || merge this one first 

Hippo.Core/Data/AppDbContext.cs, Hippo.Core/Domain/Account.cs, Hippo.Core/Domain/Tag.cs, Hippo.Core/Migrations/SqlServer/20240729174059_AccountTags.Designer.cs, Hippo.Core/Migrations/SqlServer/20240729174059_AccountTags.cs, Hippo.Core/Migrations/Sqlite/20240729174045_AccountTags.Designer.cs, Hippo.Core/Migrations/Sqlite/20240729174045_AccountTags.cs, Hippo.Core/Migrations/Sqlite/AppDbContextSqliteModelSnapshot.cs, Hippo.Web/ClientApp/src/Shared/ConfirmationDialog.tsx, Hippo.Web/ClientApp/src/Shared/ObjectTree.tsx, Hippo.Web/ClientApp/src/Shared/SearchTags.tsx, Hippo.Web/ClientApp/src/components/Account/ActiveAccounts.tsx, Hippo.Web/ClientApp/src/test/mockData.ts, Hippo.Web/ClientApp/src/types.ts, Hippo.Web/Controllers/TagsController.cs, Hippo.Web/Models/AccountModel.cs, Hippo.Web/Models/AccountTagsModel.cs
Eventually, we'll want to be able to edit, merge and delete existing tags. But I don't think that's a high priority at this point.
closes #297
=> Add account tags

Hippo.Web/ClientApp/src/Shared/Form/HipFormGroup.tsx, Hippo.Web/ClientApp/src/Shared/HipProgress.tsx, Hippo.Web/ClientApp/src/components/Account/AccountStatus.tsx, Hippo.Web/ClientApp/src/components/Order/CreateOrder.tsx, Hippo.Web/ClientApp/src/components/Order/Details.tsx, Hippo.Web/ClientApp/src/components/Order/EditOrder.tsx, Hippo.Web/ClientApp/src/components/Order/OrderForm/OrderForm.tsx, Hippo.Web/ClientApp/src/components/Order/OrderForm/StatusBar.tsx, Hippo.Web/ClientApp/src/components/Order/UpdateChartStrings.tsx, Hippo.Web/ClientApp/src/sass/_components.scss, Hippo.Web/ClientApp/src/sass/_import.scss, Hippo.Web/ClientApp/src/test/mockData.ts, Hippo.Web/ClientApp/src/types.ts, Hippo.Web/ClientApp/src/types/status.ts, Hippo.Web/Models/OrderModels/OrderDetailModel.cs
tried to consolidate status logic into one place (`status.ts`) 
styling for the form is not done, but this does the status bar. indicates on hover when an action will change the status 
https://github.com/user-attachments/assets/0bd99434-0096-4ba2-9b0e-27c4786881b6
https://github.com/user-attachments/assets/2836400f-194c-4729-8f17-ad9ee3d196f1
=> status bar

Hippo.Web/ClientApp/src/components/Order/Orders.tsx
=> Filter for quantity too

Hippo.Web/ClientApp/src/components/Order/Tables/OrdersTable.tsx, Hippo.Web/ClientApp/src/types.ts, Hippo.Web/Models/OrderModels/OrderListModel.cs
=> Progress for total and balance remaining

Hippo.Web/ClientApp/src/components/Product/Products.tsx, Hippo.Web/Controllers/ProductController.cs
=> Fix where prettier messed up my quotes

Hippo.Web/ClientApp/src/components/Order/Tables/OrdersTable.tsx, Hippo.Web/ClientApp/src/components/Product/Products.tsx, Hippo.Web/ClientApp/src/types.ts, Hippo.Web/Models/OrderModels/OrderListModel.cs
=> Change the columns in the orders UI table

Hippo.Core/Services/UserService.cs
My tweak between testing and last commit was not quite right.
=> Last fix was broken

Hippo.Core/Services/PaymentsService.cs
I had one in test, but it think the balance remaining on that one was wrong because I changed where the balance remaining was updated, so it got the old way plus the new way.
=> Check for negative balance.

Hippo.Web/ClientApp/src/App.tsx, Hippo.Web/ClientApp/src/AppNav.tsx, Hippo.Web/ClientApp/src/components/Financial/FinancialDetail.tsx, Hippo.Web/Controllers/AdminController.cs, Hippo.Web/Controllers/FinancialController.cs
And let financial admin role view/update
=> Move financial details to new controller

Hippo.Core/Services/PaymentsService.cs, Hippo.Core/Services/SlothService.cs, Hippo.Web/ClientApp/src/components/Financial/FinancialDetail.tsx, Hippo.Web/Controllers/FinancialController.cs
=> Never Auto Approve sloth

Hippo.Core/Services/SlothService.cs, Hippo.Web/Controllers/TestController.cs
The route would have to be added to the startup file
=> Process to update missing existing ones

Hippo.Web/ClientApp/src/components/Admin/Groups.tsx
=> Jumping Cursor on Edit

Hippo.Web/ClientApp/src/components/Admin/FinancialAdmins.tsx
=> Fix delete financial admin

Hippo.Web/Controllers/OrderController.cs
=> Recurring should not have expiry date

Hippo.Core/Services/PaymentsService.cs, Hippo.Web/Controllers/OrderController.cs
Needs testing at a monthly cycle with recurring and one time payments
=> Possible fix for the wrong next billing date.

Hippo.Web/Controllers/ActionController.cs, Hippo.Web/Controllers/SystemController.cs, Hippo.Web/Startup.cs
=> Add system and api endpoints to trigger puppet account sync

Hippo.Core/Data/AppDbContext.cs, Hippo.Core/Data/CustomFunctions.cs, Hippo.Core/Domain/AccessType.cs, Hippo.Core/Domain/QueuedEvent.cs, Hippo.Core/Domain/Request.cs, Hippo.Core/Extensions/RequestExtensions.cs, Hippo.Core/Hippo.Core.csproj, Hippo.Core/Models/Email/NewRequestModel.cs, Hippo.Core/Models/QueuedEventModel.cs, Hippo.Core/Models/RequestModel.cs, Hippo.Core/Services/AccountUpdateService.cs, Hippo.Core/Services/NotificationService.cs, Hippo.Core/Services/UserService.cs, Hippo.Core/Views/Emails/GroupDecision_mjml.cshtml, Hippo.Core/Views/Emails/GroupRequest_mjml.cshtml, Hippo.Jobs.Core/Hippo.Jobs.Core.csproj, Hippo.Jobs.Core/LogConfiguration.cs, Hippo.Web/ClientApp/src/Shared/requestUtils.ts, Hippo.Web/ClientApp/src/components/Account/AccountInfo.tsx, Hippo.Web/ClientApp/src/components/Account/Requests.tsx, Hippo.Web/ClientApp/src/types.ts, Hippo.Web/ClientApp/src/util/TypeChecks.ts, Hippo.Web/Controllers/AccountController.cs, Hippo.Web/Controllers/GroupController.cs, Hippo.Web/Controllers/RequestController.cs, Hippo.Web/Controllers/TagsController.cs, Hippo.Web/Hippo.Web.csproj, Hippo.Web/Models/CreateGroupModel.cs, Hippo.Web/Program.cs
Touched a lot of parts, but I don't think I went too crazy with changes. I had to update Serilog dependencies and add a package to fix a bug in how the Exceptions sink handles SqlServerExceptions. In the process, I discovered the Elasticsearch sink is deprecated. We'll have to replace that in a future update, probably whenever we upgrade to .Net8.
Closes #499
=> Add "Request Create Group" feature

Hippo.Web/ClientApp/src/components/Order/Statuses/status.ts, Hippo.Web/Controllers/OrderController.cs
=> Allow closed recurring order to be archived.

Hippo.Web/ClientApp/src/components/Account/RequestForm.tsx
=> Tweak some text in RequestForm

Hippo.Web/ClientApp/package.json, Hippo.Web/ClientApp/src/Shared/Table/HelperFunctions.ts, Hippo.Web/ClientApp/src/components/Account/ActiveAccounts.tsx, Hippo.Web/ClientApp/src/components/Group/GroupMembers.tsx, Hippo.Web/ClientApp/src/components/Order/HistoryTable.tsx, Hippo.Web/ClientApp/src/components/Order/PaymentTable.tsx, Hippo.Web/ClientApp/src/components/Order/Tables/OrdersTable.tsx, Hippo.Web/ClientApp/src/components/Report/Tables/PaymentsTable.tsx
=>  Fix date sorting on some tables 

Hippo.Core/Views/Emails/AccountDecision_mjml.cshtml, Hippo.Core/Views/Emails/GroupDecision_mjml.cshtml, Hippo.Web/ClientApp/src/components/Account/AccountInfo.tsx, Hippo.Web/ClientApp/src/components/Account/RequestForm.tsx, Hippo.Web/ClientApp/src/components/ClusterAdmin/Clusters.tsx
=> Update help links

Hippo.Core/Services/AccountUpdateYamlService.cs, Hippo.Web/ClientApp/src/Shared/AppContext.ts, Hippo.Web/ClientApp/src/components/Account/AccountInfo.tsx, Hippo.Web/ClientApp/src/components/Group/GroupMembers.tsx, Hippo.Web/ClientApp/src/test/mockData.ts, Hippo.Web/ClientApp/src/types.ts, Hippo.Web/Controllers/GroupController.cs, Hippo.Web/Models/Settings/FeatureFlagSettings.cs, Hippo.Web/Program.cs, Hippo.Web/Views/Shared/_Layout.cshtml, Hippo.Web/appsettings.json
Structured it to be easily extendable in order to facilitate more frequent pushes to prod.
=> Update feature flags
