ucdavis/hippo

- Hippo.Web/ClientApp/src/App.tsx
- Hippo.Web/ClientApp/src/Shared/AppContext.ts
- Hippo.Web/ClientApp/src/components/AccountInfo.tsx
- Hippo.Web/ClientApp/src/components/Home.tsx
- Hippo.Web/ClientApp/src/components/RequstForm.tsx
Pretty proud of this one, makes it easy for child pages to mutate the account as it changes.  Perhaps we might want to create a separate context just for account info (separate than user) in the future -- for now this seems just fine.  So now the request form just submits to the server, then sets the context and redirects to home
> Make context mutable, update request push method

- Hippo.Core/Models/AccountDetail.cs
- Hippo.Core/Services/UserService.cs
- Hippo.Web/ClientApp/src/App.test.tsx
- Hippo.Web/ClientApp/src/App.tsx
- Hippo.Web/ClientApp/src/AppNav.tsx
- Hippo.Web/ClientApp/src/ConditionalRoute.tsx
- Hippo.Web/ClientApp/src/Shared/AppContext.ts
- Hippo.Web/ClientApp/src/Shared/ShowFor.tsx
- Hippo.Web/ClientApp/src/components/Account/AccountInfo.tsx
- Hippo.Web/ClientApp/src/components/Account/ApproveAccounts.test.tsx
- Hippo.Web/ClientApp/src/components/Account/ApproveAccounts.tsx
- Hippo.Web/ClientApp/src/components/Account/Multiple.tsx
- Hippo.Web/ClientApp/src/components/Account/RequestForm.tsx
- Hippo.Web/ClientApp/src/components/Account/SponsoredAccounts.tsx
- Hippo.Web/ClientApp/src/components/Admin/AdminApproveAccounts.tsx
- Hippo.Web/ClientApp/src/components/Admin/AdminUsers.tsx
- Hippo.Web/ClientApp/src/components/Admin/Sponsors.tsx
- Hippo.Web/ClientApp/src/components/Home.test.tsx
- Hippo.Web/ClientApp/src/components/Home.tsx
- Hippo.Web/ClientApp/src/test/mockData.ts
- Hippo.Web/ClientApp/src/types.ts
- Hippo.Web/Controllers/AccountController.cs
- Hippo.Web/Controllers/AdminController.cs
- Hippo.Web/Controllers/SuperController.cs
- Hippo.Web/Extensions/AuthenticationExtensions.cs
- Hippo.Web/Extensions/QueryableExtensions.cs
- Hippo.Web/Handlers/VerifyRoleAccessHandler.cs
- Hippo.Web/Startup.cs
- Hippo.Web/Views/Shared/_Layout.cshtml
Handles structure of multi-cluster support, including all user activity and some example admin activity.
All API endpoints client/server have been updated to take cluster as url param.  Components have been updated to check this param and controllers expose it.  LINQ queries now use custom `InCluster()` filter for most queries.
A few admin functions still need to be updated (see TODO in adminController.cs).  Additionally admin permissions checked by auth policy need to be updated to handle cluster as well.
> Multi-cluster support

- Hippo.Web/Controllers/AccountController.cs
Automatically approve requests for existing accounts, do not notify the sponsor, and update SSH keys.
> Approve requests for existing accounts

- Hippo.Web/Services/YamlService.cs
accidentally output the whole cluster obj rather than cluster name in the serialized yaml obj
> fixed an oops in serialized object

- .vscode/launch.json
- Hippo.Core/Hippo.Core.csproj
- Hippo.Core/Models/PuppetDetails.cs
- Hippo.Core/Models/Settings/PuppetSettings.cs
- Hippo.Core/Services/PuppetService.cs
- Hippo.Jobs.Core/Hippo.Jobs.Core.csproj
- Hippo.Jobs.Core/JobBase.cs
- Hippo.Jobs.Core/LogConfiguration.cs
- Hippo.Jobs.Core/Properties/launchSettings.json
- Hippo.Jobs.PuppetSync/Hippo.Jobs.PuppetSync.csproj
- Hippo.Jobs.PuppetSync/Program.cs
- Hippo.Jobs.PuppetSync/appsettings.json
- Hippo.Jobs.PuppetSync/run.cmd
- Hippo.Jobs.PuppetSync/settings.job
- Hippo.Web/Hippo.Web.csproj
- Hippo.Web/appsettings.json
- azure-pipelines-web.yml
- hippo.sln
Doesn't actually do anything right now. Though it will pull data if you tweak `var accounts = await puppetService.GetPuppetDetails("tbd...");` to actually point to a yaml file in the accounts repo. I didn't want to hard-code that. I'm thinking the yaml file paths should probably be stored in the `dbo.Clusters` table, but wanted to get an alternative App Service running, along with its own db so that deployments from merges to `main` and `dev` don't have migrations clobbering each other. So this should automatically deploy to https://hippo-dev-test.azurewebsites.net
> Initial implementation of Hippo.Jobs.PuppetSync

- Hippo.Web/ClientApp/src/components/Admin/Groups.tsx
switch accessor to simple name and use Cell for custom rendering.  this way filtering still works on string name value.  Closes #247
> filter by name

- Hippo.Web/ClientApp/src/components/Account/ActiveAccounts.tsx
- Hippo.Web/ClientApp/src/components/Account/Requests.tsx
- Hippo.Web/ClientApp/src/components/Admin/GroupAdmins.tsx
- Hippo.Web/ClientApp/src/components/Admin/Groups.tsx
- Hippo.Web/ClientApp/src/util/StringHelpers.ts
I applied the accessor/Cell fix to the three remaining table columns that contain the `<GroupNameWithTooltip />` component. Also updated the accessors to include more details from `GroupModel` for better filtering.
Closes #247
> Make all group columns sortable and filterable

- Hippo.Core/Extensions/StringExtensions.cs
- Hippo.Core/Hippo.Core.csproj
- Hippo.Core/Models/Settings/PuppetSettings.cs
- Hippo.Core/Services/PuppetService.cs
- Hippo.Jobs.PuppetSync/Program.cs
- Hippo.Jobs.PuppetSync/appsettings.json
- Hippo.Web/appsettings.json
I couldn't use Octokit's suggestion to use the GitHubJwt nuget package for generating the jwt, because BouncyCastle would fail to read the pem key no matter how I formatted it. And just about all the examples out there are based on BouncyCastle. But it turns out to be not too complex just using `System.Security.Cryptography` directly.
I've updated secrets in 1pass.
> Replace personal access token with github app authentication 

- Hippo.Web/Controllers/RequestController.cs
Quick fix. It will need to deploy to prod soon. Tested approve process on hippo-test.
This was caused by a refactor to eliminate foreign keys to Groups and Accounts so that they could be easily deleted. Navigation properties were changed to just strings. I'm surprised the Include extension method doesn't restrict the property type to at least be a class.
> Don't call Include() on a string property

- Hippo.Core/Domain/Account.cs
- Hippo.Core/Domain/Group.cs
- Hippo.Core/Migrations/SqlServer/20240409233559_PuppetResourceData.Designer.cs
- Hippo.Core/Migrations/SqlServer/20240409233559_PuppetResourceData.cs
- Hippo.Core/Migrations/SqlServer/AppDbContextSqlServerModelSnapshot.cs
- Hippo.Core/Migrations/Sqlite/20240409233551_PuppetResourceData.Designer.cs
- Hippo.Core/Migrations/Sqlite/20240409233551_PuppetResourceData.cs
- Hippo.Core/Models/GroupModel.cs
- Hippo.Core/Services/AccountSyncService.cs
- Hippo.Core/Services/PuppetService.cs
- Hippo.Web/ClientApp/src/Shared/ObjectTree.tsx
- Hippo.Web/ClientApp/src/components/Account/AccountInfo.tsx
- Hippo.Web/ClientApp/src/components/Account/ActiveAccounts.tsx
- Hippo.Web/ClientApp/src/components/Account/RequestForm.tsx
- Hippo.Web/ClientApp/src/components/Account/Requests.test.tsx
- Hippo.Web/ClientApp/src/components/Account/Requests.tsx
- Hippo.Web/ClientApp/src/components/Admin/Groups.tsx
- Hippo.Web/ClientApp/src/components/Admin/TransferSponsor.tsx
- Hippo.Web/ClientApp/src/components/Home.test.tsx
- Hippo.Web/ClientApp/src/test/mockData.ts
- Hippo.Web/ClientApp/src/types.ts
- Hippo.Web/ClientApp/src/util/api.ts
- Hippo.Web/Controllers/AccountController.cs
- Hippo.Web/Controllers/GroupController.cs
- Hippo.Web/Models/AccountModel.cs
- Hippo.Web/Models/UpdateGroupModel.cs
I went with a generic collapsible `ObjectTree` component for displaying resource data. Not sure if @cydoval should have a go yet at prettying it up. Maybe @acgetchell will have some feedback?
Group data:
Account data:
> Sync and display puppet resource data

- Hippo.Core/Data/AppDbContext.cs
- Hippo.Core/Domain/Account.cs
- Hippo.Core/Domain/Group.cs
- Hippo.Core/Domain/QueuedEvent.cs
- Hippo.Core/Domain/Request.cs
- Hippo.Core/Extensions/RequestExtensions.cs
- Hippo.Core/Extensions/ValueConversionExtensions.cs
- Hippo.Core/Models/GroupModel.cs
- Hippo.Core/Models/QueuedEventModel.cs
- Hippo.Core/Models/RequestModel.cs
- Hippo.Core/Services/AccountUpdateService.cs
- Hippo.Core/Services/PuppetService.cs
- Hippo.Core/Utilities/JsonHelper.cs
- Hippo.Web/ClientApp/src/components/Account/AccountInfo.tsx
- Hippo.Web/ClientApp/src/components/Account/ActiveAccounts.tsx
- Hippo.Web/ClientApp/src/components/Account/RequestForm.tsx
- Hippo.Web/ClientApp/src/components/Account/Requests.test.tsx
- Hippo.Web/ClientApp/src/components/Account/Requests.tsx
- Hippo.Web/ClientApp/src/components/Admin/Groups.tsx
- Hippo.Web/ClientApp/src/components/Admin/TransferSponsor.tsx
- Hippo.Web/ClientApp/src/components/Home.test.tsx
- Hippo.Web/ClientApp/src/test/mockData.ts
- Hippo.Web/ClientApp/src/types.ts
- Hippo.Web/ClientApp/src/util/api.ts
- Hippo.Web/Controllers/EventQueueController.cs
- Hippo.Web/Models/AccountModel.cs
- Hippo.Web/Views/Shared/_Layout.cshtml
Some of the json Data columns were being passed to the client as strings because only the client is concerned with their contents, and because the data makes extensive use of unions, which aren't easily represented with C# types. But deserializing the Data properties client-side was ugly and error-prone. Making the Data type `JsonElement` seemed like a nice compromise, they're still loosely typed server-side, but no need to parse them client-side.
I temporarily generated a new migration to verify that the ValueConverter didn't change anything in the schema or the model snapshot. Also verified that it didn't impact the bulk operations performed by the `AccountSyncService`.
> Data serialization refactor

- Hippo.Web/ClientApp/src/Shared/Form/FormField.tsx
- Hippo.Web/ClientApp/src/components/Order/Details.tsx
- Hippo.Web/ClientApp/src/components/Order/MetaDataFields.tsx
- Hippo.Web/ClientApp/src/components/Order/OrderForm.tsx
- Hippo.Web/ClientApp/src/components/Order/OrderFormTotalFields.tsx
useWatch() instead of handling the change ourselves. moved it into its own component, which will only rerender when the watched values change. now we don't have to do anything special to validate the total, just `min`, but to trigger the validation you have to add `deps="total"` to the fields it relies on. 
i stopped passing disabled into the `register()` because it sets the value to undefined and was causing weird issues, now the disabled prop only gets passed directly to the input
> useWatch instead of manually handling change

- Hippo.Core/Data/AppDbContext.cs
- Hippo.Core/Domain/History.cs
- Hippo.Core/Domain/TempGroup.cs
- Hippo.Core/Domain/TempKerberos.cs
- Hippo.Core/Migrations/SqlServer/20240711203741_RefactorAccountSync.Designer.cs
- Hippo.Core/Migrations/SqlServer/20240711203741_RefactorAccountSync.cs
- Hippo.Core/Migrations/Sqlite/20240711203730_RefactorAccountSync.Designer.cs
- Hippo.Core/Migrations/Sqlite/20240711203730_RefactorAccountSync.cs
- Hippo.Core/Migrations/Sqlite/AppDbContextSqliteModelSnapshot.cs
- Hippo.Core/Services/AccountSyncService.cs
- Hippo.Core/Services/HistoryService.cs
I verified that it is correctly removing group memberships.
I wasn't sure about using a tuple `(a.ClusterId, a.Kerberos)` as a dictionary key, but it seemed cleaner than defining a wrapper type and manually implementing all the hash/equality stuff to be able to use it as a key.
> Refactor account sync (merge all clusters at once)

- Hippo.Core/Services/AccountUpdateYamlService.cs
Not sure if there's any way to really test this. It should be safe to rely on only the presence of `account.Key`, since that was thoroughly validated at the time an account was requested...
https://github.com/ucdavis/hippo/blob/05086736d396b85df548b9935ad0415031536ef0/Hippo.Web/Controllers/AccountController.cs#L108-L137
Closes #289
> Leave sshkey out of yaml when disabled/not relevant

- Hippo.Web/ClientApp/src/components/Order/BillingsFields.tsx
> Link to finjector

- Hippo.Web/ClientApp/src/components/Order/Orders.tsx
> Search the order id in the table

- .vscode/launch.json
- Hippo.Core/Domain/Account.cs
- Hippo.Core/Domain/Cluster.cs
- Hippo.Core/Extensions/ClusterExtensions.cs
- Hippo.Core/Migrations/SqlServer/20250401203634_AcceptableUse.Designer.cs
- Hippo.Core/Migrations/SqlServer/20250401203634_AcceptableUse.cs
- Hippo.Core/Migrations/Sqlite/20250401203623_AcceptableUse.Designer.cs
- Hippo.Core/Migrations/Sqlite/20250401203623_AcceptableUse.cs
- Hippo.Core/Migrations/Sqlite/AppDbContextSqliteModelSnapshot.cs
- Hippo.Core/Models/AccountDetail.cs
- Hippo.Core/Models/ClusterModel.cs
- Hippo.Core/Models/RequestModel.cs
- Hippo.Core/Services/AccountUpdateService.cs
- Hippo.Core/Services/UserService.cs
- Hippo.Web/ClientApp/src/App.tsx
- Hippo.Web/ClientApp/src/Shared/RequireAupAgreement.tsx
- Hippo.Web/ClientApp/src/components/Account/AccountInfo.tsx
- Hippo.Web/ClientApp/src/components/Account/RequestForm.tsx
- Hippo.Web/ClientApp/src/components/Account/Requests.test.tsx
- Hippo.Web/ClientApp/src/components/Account/Requests.tsx
- Hippo.Web/ClientApp/src/components/ClusterAdmin/Clusters.tsx
- Hippo.Web/ClientApp/src/test/mockData.ts
- Hippo.Web/ClientApp/src/types.ts
- Hippo.Web/Controllers/AccountController.cs
- Hippo.Web/Controllers/ClusterAdminController.cs
- Hippo.Web/Models/AccountCreateModel.cs
- Hippo.Web/Models/AccountModel.cs
If an existing account's AUP agreement date doesn't exist or is expired, the user will be presented with the following on all applicable routes...
The cluster edit form...
I've only run this against my local db. If you want to run it against test, you'll need to go into the cluster admin page and add a AUP url and date.
If a cluster hasn't configured an AUP, the agreement UI isn't shown, and the user is not blocked.
Closes #513
> Require AUP agreement on account request and when AUP changes

- Hippo.Core/Services/AccountSyncService.cs
- Hippo.Core/Utilities/JsonHelper.cs
I haven't actually been able to reproduce accounts being updated every day. What I think may be happening is a group with many accounts gets its QOS updated, resulting in every member account getting a corresponding update to its Json Data property, since QOS references are expanded during sync. So the json normalization is probably unnecessary, but it doesn't put much of a dent in performance.
Closes #539
> Disable account delete and normalize account.data

- Hippo.Web/ClientApp/src/Shared/ConfirmationDialog.tsx
It wasn't the the return value of the canConfirm function that was the problem. It was the fact that the hook maintains returnValue state across dialog invocations. It now clears that state on each confirmation/dismissal.
Closes #572
> Reset returnValue after dialog closes

- Hippo.Web/ClientApp/src/App.tsx
- Hippo.Web/ClientApp/src/AppNav.tsx
- Hippo.Web/ClientApp/src/Shared/requestUtils.ts
- Hippo.Web/ClientApp/src/Shared/usePermissions.ts
- Hippo.Web/ClientApp/src/components/Account/Requests.tsx
- Hippo.Web/ClientApp/src/components/Group/GroupInfo.tsx
- Hippo.Web/ClientApp/src/test/mockData.ts
Cluster admins can now see Requests and Accounts, while only Group admins can approve/reject Requests for their group.
Closes #590
> Fix group permissions for cluster admins
